In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
shifts_df = pd.read_csv('shifts.csv')

In [3]:
hcp_df = pd.read_csv('hcps.csv')

In [4]:
shifts_df.head()

,id,hcp_id,hcf_id,agent_type,charge,created_at,shift_start,shift_type,is_cancelled,is_verified
0,5f18adbb6145d4001773f69f,5b5635b34afc8f0014a40433,5e6662c827dbec0016767584,CNA,28.0,07/22,08/17,am,True,False
1,5f18ade019ed420017bb14c3,5b5635b34afc8f0014a40433,5e6662c827dbec0016767584,CNA,28.0,07/22,08/24,am,True,False
2,5f18adeb19ed420017bb14c6,5b5635b34afc8f0014a40433,5e6662c827dbec0016767584,CNA,28.0,07/22,08/31,am,True,False
3,5f18adf43d5e0b0017498604,5b5635b34afc8f0014a40433,5e6662c827dbec0016767584,CNA,42.0,07/22,09/07,am,True,False
4,5f18ae003d5e0b001749860f,5b5635b34afc8f0014a40433,5e6662c827dbec0016767584,CNA,28.0,07/22,09/14,am,True,False

In [5]:
shifts_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3682 entries, 0 to 3681
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            3682 non-null   object
 1   hcp_id        3682 non-null   object
 2   hcf_id        3682 non-null   object
 3   agent_type    3682 non-null   object
 4   charge        3682 non-null   float64
 5   created_at    3682 non-null   object
 6   shift_start   3682 non-null   object
 7   shift_type    3682 non-null   object
 8   is_cancelled  3682 non-null   bool
 9   is_verified   3682 non-null   bool
dtypes: bool(2), float64(1), object(7)
memory usage: 237.4+ KB

In [6]:
#run code only once or else it will keep adding 2019
shifts_df['created_at'] = shifts_df['created_at'] + '/2019'
shifts_df['shift_start'] = shifts_df['shift_start'] + '/2019'

In [7]:
shifts_df['created_at'] = pd.to_datetime(shifts_df['created_at'], format = '%m/%d/%Y')
shifts_df['shift_start'] = pd.to_datetime(shifts_df['shift_start'], format = '%m/%d/%Y')
shifts_df

,id,hcp_id,hcf_id,agent_type,charge,created_at,shift_start,shift_type,is_cancelled,is_verified
0,5f18adbb6145d4001773f69f,5b5635b34afc8f0014a40433,5e6662c827dbec0016767584,CNA,28.0,2019-07-22,2019-08-17,am,True,False
1,5f18ade019ed420017bb14c3,5b5635b34afc8f0014a40433,5e6662c827dbec0016767584,CNA,28.0,2019-07-22,2019-08-24,am,True,False
2,5f18adeb19ed420017bb14c6,5b5635b34afc8f0014a40433,5e6662c827dbec0016767584,CNA,28.0,2019-07-22,2019-08-31,am,True,False
3,5f18adf43d5e0b0017498604,5b5635b34afc8f0014a40433,5e6662c827dbec0016767584,CNA,42.0,2019-07-22,2019-09-07,am,True,False
4,5f18ae003d5e0b001749860f,5b5635b34afc8f0014a40433,5e6662c827dbec0016767584,CNA,28.0,2019-07-22,2019-09-14,am,True,False
...,...,...,...,...,...,...,...,...,...,...
3677,5f5a8a6ab97ca100165a1d0b,5f592fac99d71b00161c33c7,5e8f6513fb94ef0016a870a3,CNA,28.0,2019-09-10,2019-09-21,am,False,False
3678,5f68f8d0a39ebc00160edfa9,5f592fac99d71b00161c33c7,5e8f6513fb94ef0016a870a3,CNA,28.0,2019-09-21,2019-09-26,am,False,False
3679,5f68f8db861401001614c52d,5f592fac99d71b00161c33c7,5e8f6513fb94ef0016a870a3,CNA,28.0,2019-09-21,2019-09-27,am,False,False
3680,5f68f8ee861401001614c533,5f592fac99d71b00161c33c7,5e8f6513fb94ef0016a870a3,CNA,28.0,2019-09-21,2019-09-28,am,False,False
3681,5f68f904a39ebc00160edfbb,5f592fac99d71b00161c33c7,5e8f6513fb94ef0016a870a3,CNA,28.0,2019-09-21,2019-09-30,am,False,False

In [8]:
shifts_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3682 entries, 0 to 3681
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            3682 non-null   object
 1   hcp_id        3682 non-null   object
 2   hcf_id        3682 non-null   object
 3   agent_type    3682 non-null   object
 4   charge        3682 non-null   float64
 5   created_at    3682 non-null   datetime64[ns]
 6   shift_start   3682 non-null   datetime64[ns]
 7   shift_type    3682 non-null   object
 8   is_cancelled  3682 non-null   bool
 9   is_verified   3682 non-null   bool
dtypes: bool(2), datetime64[ns](2), float64(1), object(5)
memory usage: 237.4+ KB

In [21]:
shifts_df['Days to Fill Shift'] = abs((shifts_df['created_at'] - shifts_df['shift_start'])/np.timedelta64(1, 'D'))
shifts_df.head(20)

,id,hcp_id,hcf_id,agent_type,charge,created_at,shift_start,shift_type,is_cancelled,is_verified,Days to Fill Shift
0,5f18adbb6145d4001773f69f,5b5635b34afc8f0014a40433,5e6662c827dbec0016767584,CNA,28.0,2019-07-22,2019-08-17,am,True,False,26.0
1,5f18ade019ed420017bb14c3,5b5635b34afc8f0014a40433,5e6662c827dbec0016767584,CNA,28.0,2019-07-22,2019-08-24,am,True,False,33.0
2,5f18adeb19ed420017bb14c6,5b5635b34afc8f0014a40433,5e6662c827dbec0016767584,CNA,28.0,2019-07-22,2019-08-31,am,True,False,40.0
3,5f18adf43d5e0b0017498604,5b5635b34afc8f0014a40433,5e6662c827dbec0016767584,CNA,42.0,2019-07-22,2019-09-07,am,True,False,47.0
4,5f18ae003d5e0b001749860f,5b5635b34afc8f0014a40433,5e6662c827dbec0016767584,CNA,28.0,2019-07-22,2019-09-14,am,True,False,54.0
5,5f18ae0b3d5e0b0017498612,5b5635b34afc8f0014a40433,5e6662c827dbec0016767584,CNA,28.0,2019-07-22,2019-09-21,am,True,False,61.0
6,5f18ae156145d4001773f6b2,5b5635b34afc8f0014a40433,5e6662c827dbec0016767584,CNA,28.0,2019-07-22,2019-09-28,am,True,False,68.0
7,5f18ae1f19ed420017bb14da,5b5635b34afc8f0014a40433,5e6662c827dbec0016767584,CNA,28.0,2019-07-22,2019-10-05,am,True,False,75.0
8,5f18ae273d5e0b0017498617,5b5635b34afc8f0014a40433,5e6662c827dbec0016767584,CNA,28.0,2019-07-22,2019-10-12,am,True,False,82.0
9,5f18ae3619ed420017bb14e2,5b5635b34afc8f0014a40433,5e6662c827dbec0016767584,CNA,28.0,2019-07-22,2019-10-19,am,True,False,89.0
10,5f18ae4cf3688300177c081f,5b5635b34afc8f0014a40433,5e6662c827dbec0016767584,CNA,28.0,2019-07-22,2019-10-26,am,True,False,96.0
11,5efccad4191a970017d3e28e,5b6dda6d6ce3150014cc74c6,5bd20a2c2f1b850004d0f55e,LVN,42.0,2019-07-01,2019-07-22,am,True,False,21.0
12,5efccaf98be2570017d3e40e,5b6dda6d6ce3150014cc74c6,5bd20a2c2f1b850004d0f55e,LVN,42.0,2019-07-01,2019-07-30,am,True,False,29.0
13,5f5c43282f95160016b74248,5b6dda6d6ce3150014cc74c6,5bd20a2c2f1b850004d0f55e,LVN,42.0,2019-09-12,2019-09-13,noc,False,True,1.0
14,5f5c432d2f95160016b7424b,5b6dda6d6ce3150014cc74c6,5bd20a2c2f1b850004d0f55e,LVN,42.0,2019-09-12,2019-09-14,noc,False,True,2.0
15,5f5c43362f95160016b7424e,5b6dda6d6ce3150014cc74c6,5bd20a2c2f1b850004d0f55e,LVN,42.0,2019-09-12,2019-09-19,noc,True,False,7.0
16,5f6009db3f190e001656402b,5b6dda6d6ce3150014cc74c6,5e8dce39ee2690001638ce46,LVN,51.0,2019-09-15,2019-10-02,noc,False,False,17.0
17,5f6009e63f190e001656402f,5b6dda6d6ce3150014cc74c6,5e8dce39ee2690001638ce46,LVN,51.0,2019-09-15,2019-10-08,noc,False,False,23.0
18,5f6009ed3f190e0016564032,5b6dda6d6ce3150014cc74c6,5e8dce39ee2690001638ce46,LVN,51.0,2019-09-15,2019-10-14,noc,False,False,29.0
19,5f6009f33f190e0016564035,5b6dda6d6ce3150014cc74c6,5e8dce39ee2690001638ce46,LVN,51.0,2019-09-15,2019-10-20,noc,False,False,35.0

In [22]:
#Isolate for those non-cancelled, verified shifts
verified_shifts_df = shifts_df[(shifts_df['is_cancelled'] == False) & (shifts_df['is_verified'] == True)]
verified_shifts_df.head(20)

,id,hcp_id,hcf_id,agent_type,charge,created_at,shift_start,shift_type,is_cancelled,is_verified,Days to Fill Shift
13,5f5c43282f95160016b74248,5b6dda6d6ce3150014cc74c6,5bd20a2c2f1b850004d0f55e,LVN,42.0,2019-09-12,2019-09-13,noc,False,True,1.0
14,5f5c432d2f95160016b7424b,5b6dda6d6ce3150014cc74c6,5bd20a2c2f1b850004d0f55e,LVN,42.0,2019-09-12,2019-09-14,noc,False,True,2.0
22,5f08cef77685200017c83a7e,5b6e37ff625376001402de0f,5be0b0d2ba64030004d2117c,CNA,35.0,2019-07-10,2019-07-21,am,False,True,11.0
23,5f08cf0b7685200017c83a87,5b6e37ff625376001402de0f,5be0b0d2ba64030004d2117c,CNA,35.0,2019-07-10,2019-07-23,am,False,True,13.0
24,5f458ae65b9cad0016cd7b20,5b6e37ff625376001402de0f,5b70ed73e318270014cd6bee,CNA,24.0,2019-08-25,2019-09-16,pm,False,True,22.0
29,5f51699faeb9cb0016ef8921,5b6e37ff625376001402de0f,5f2ae7490153c70016c840f5,CNA,45.0,2019-09-03,2019-09-05,am,False,True,2.0
30,5f52b8e03d95610016e0b83d,5b6e37ff625376001402de0f,5f2ae7490153c70016c840f5,CNA,49.5,2019-09-04,2019-09-07,am,False,True,3.0
31,5f52cacd8c405c0016d31945,5b6e37ff625376001402de0f,5f2ae7490153c70016c840f5,CNA,45.0,2019-09-04,2019-09-05,pm,False,True,1.0
32,5f5807275684fc001618cf6c,5b6e37ff625376001402de0f,5bb380e8945fd200046cad4c,CNA,24.0,2019-09-08,2019-09-14,am,False,True,6.0
33,5f2dfa20e1bcf700161e1e3f,5bb684553e5353000430e587,5f2df9b9dfb6250016bdff3c,CNA,35.0,2019-08-08,2019-08-08,am,False,True,0.0
34,5f30911834902e001637d138,5bb684553e5353000430e587,5f2df9b9dfb6250016bdff3c,CNA,35.0,2019-08-10,2019-08-10,custom,False,True,0.0
35,5f3764647ec92000166d270f,5bb684553e5353000430e587,5f305015f8d05400161fa931,CNA,35.0,2019-08-15,2019-08-15,pm,False,True,0.0
36,5f3764887ec92000166d2715,5bb684553e5353000430e587,5f305015f8d05400161fa931,CNA,35.0,2019-08-15,2019-08-16,pm,False,True,1.0
38,5f3883512e355a00164bc207,5bb684553e5353000430e587,5f305015f8d05400161fa931,CNA,35.0,2019-08-16,2019-08-18,pm,False,True,2.0
39,5f38836f2db6d00016d6f848,5bb684553e5353000430e587,5f305015f8d05400161fa931,CNA,35.0,2019-08-16,2019-08-20,pm,False,True,4.0
40,5f3aadafc641af0016e4a4de,5bb684553e5353000430e587,5f305015f8d05400161fa931,CNA,35.0,2019-08-17,2019-08-19,pm,False,True,2.0
41,5f3abf67f76e09001623cbc9,5bb684553e5353000430e587,5bb380e8945fd200046cad4c,CNA,24.0,2019-08-17,2019-08-31,pm,False,True,14.0
44,5f3f0d3199acd00016d2a723,5bb684553e5353000430e587,5f305015f8d05400161fa931,CNA,35.0,2019-08-20,2019-08-21,pm,False,True,1.0
45,5f3f0d34ce2e6a00166c4147,5bb684553e5353000430e587,5f305015f8d05400161fa931,CNA,35.0,2019-08-20,2019-08-22,pm,False,True,2.0
47,5f483b89f46eec0016416a43,5bb684553e5353000430e587,5f305015f8d05400161fa931,CNA,35.0,2019-08-27,2019-08-22,custom,False,True,5.0

In [25]:
instant_fill = verified_shifts_df[verified_shifts_df['Days to Fill Shift'] == 0.0]
instant_fill

,id,hcp_id,hcf_id,agent_type,charge,created_at,shift_start,shift_type,is_cancelled,is_verified,Days to Fill Shift
33,5f2dfa20e1bcf700161e1e3f,5bb684553e5353000430e587,5f2df9b9dfb6250016bdff3c,CNA,35.0,2019-08-08,2019-08-08,am,False,True,0.0
34,5f30911834902e001637d138,5bb684553e5353000430e587,5f2df9b9dfb6250016bdff3c,CNA,35.0,2019-08-10,2019-08-10,custom,False,True,0.0
35,5f3764647ec92000166d270f,5bb684553e5353000430e587,5f305015f8d05400161fa931,CNA,35.0,2019-08-15,2019-08-15,pm,False,True,0.0
56,5f571f56ad1d1d00164b546d,5bb684553e5353000430e587,5bb380e8945fd200046cad4c,CNA,26.0,2019-09-08,2019-09-08,noc,False,True,0.0
60,5f6257b94f29de0016e93fdb,5bb684553e5353000430e587,5f3b2d6cf76e09001623f54e,CNA,100.0,2019-09-16,2019-09-16,custom,False,True,0.0
...,...,...,...,...,...,...,...,...,...,...,...
3568,5f613f6ac05b9b0016f518fa,5f380af62e355a00164ba76e,5f3a6ea070b0d80016601d89,Medical Assistant,24.0,2019-09-15,2019-09-15,am,False,True,0.0
3585,5f446d0714eabb0016314d63,5f3ad53a2232520016d2777a,5eebe1ec00957c0017a41c49,CNA,31.0,2019-08-25,2019-08-25,custom,False,True,0.0
3648,5f57a36b6ed44c001613a16d,5f4bbd29dcab30001604da6a,5f3a6ea070b0d80016601d89,Medical Assistant,24.0,2019-09-08,2019-09-08,am,False,True,0.0
3652,5f5f727363fc36001641dff6,5f4bbd29dcab30001604da6a,5f3a6ea070b0d80016601d89,Medical Assistant,24.0,2019-09-14,2019-09-14,am,False,True,0.0
3653,5f613f6bc05b9b0016f518fd,5f4bbd29dcab30001604da6a,5f3a6ea070b0d80016601d89,Medical Assistant,24.0,2019-09-15,2019-09-15,am,False,True,0.0

In [28]:
hcp_to_hcf = verified_shifts_df.groupby('hcp_id')['hcf_id'].nunique().to_frame()
hcp_to_hcf

                          hcf_id
hcp_id
5b6dda6d6ce3150014cc74c6       1
5b6e37ff625376001402de0f       4
5bb684553e5353000430e587       7
5be4c820a3acae0004af0833       2
5bebb6bf19a24e000424b1a0       6
...                          ...
5f4803b6c0b6bd001607cb17       1
5f4a9a63c682c20016d922cf       1
5f4bbd29dcab30001604da6a       1
5f57d0776ed44c001613b1d0       1
5f592fac99d71b00161c33c7       2

[191 rows x 1 columns]

In [29]:
#It's different frequencies than the previous ones, because it only includes verified, non-cancelled shifts 
#190 workers here vs 200 in the other frequency graph
#10 workers had all their shifts completely cancelled 
hcp_to_hcf['hcf_id'].value_counts()

1     94
2     33
3     22
4     13
7      8
6      8
5      7
9      3
8      2
11     1
Name: hcf_id, dtype: int64

In [ ]:
#realizing how hard it is to define consistent vs on-demand shifts
#Like is that consecutive or weekly shifts for consistent shifts
#How many workers have worked shifts weekly, monthly, even daily
#Also it's for 200 workers, so might be tricky to do a case by case analysis

In [ ]:
#Looking at the worker who worked at 11 different facilities (originally it was 2)